version: '3.9'

services:
  chat-front:
    restart: always
    command: npm start
    container_name: chat-front
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
    ports:
     - "3000:3000"
    volumes:
      - '.:/app'
      - '/app/node_modules'
    env_file:
      - .env.dev